### ISSUE TITLE
Compatibility !!!

### ISSUE THREAD

**Issue by RabieMohimane** [CardinalNow/Android-CircleProgressIndicator#11]
It is not  compatible with all android version :
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.github.CardinalNow:Android-CircleProgressIndicator:v0.2] C:\Users\Administrateur\Desktop\Pompes\app\build\intermediates\exploded-aar\com.github.CardinalNow\Android-CircleProgressIndicator\v0.2\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="com.cardinalsolutions.progressindicator" to force usage

**Comment by RabieMohimane** [comment]
how to modify ring size?

**Comment by jacobhyphenated** [comment]
**Compatibility**
This library has support set to API 16. You may try to use it on a lower API version at your own risk.
Adding this line to your manifest will override the API restriction in the library:

```
<uses-sdk android:minSdkVersion="15"
        tools:overrideLibrary="com.cardinalsolutions.progressindicator"/>
```

**Changing the ring radius**
If you want to change the size of the circular progress bar, you need to change the radius.

In a resources xml, override the circleProgressRadius dimension value. In your case, if you want a radius of 10dp and a thickness of 2dp, use:

```
<dimen name="circleProgressRadius">10dp</dimen>
<dimen name="circleProgressThickness">2dp</dimen>
```

See the Readme for other configurable values.

**Comment by RabieMohimane** [comment]
thank you a lot jacobhyphenated  :)
