### ISSUE TITLE
Does not work on Nexus 7 (v5.0.2)

### ISSUE THREAD

**Issue by 022y** [CardinalNow/Android-CircleProgressIndicator#2]
On Nexus 7 (v5.0.2) indicator always shows 100%.
![screenshot_2015-02-04-17-29-17 1](https://cloud.githubusercontent.com/assets/7025443/6042207/c7628606-ac93-11e4-8f5a-49cf60d22cb4.png)

With Xiaome MI2 (v4.1.1) everything works fine.

**Comment by kingws** [comment]
Hmm, I'll check that out this evening.  I've tested on a Nexus 7 before with no issues.  Thanks for the info.

**Comment by kingws** [comment]
I apologize for the delayed response, but I just checked in the fix for this bug.  The default value for android:useLevel under the tag incorrectly changed to false in Android L. The work around is to set the value in the shape drawable XML to true.
