### ISSUE TITLE
Error compiling from Gradle

### ISSUE THREAD

**Issue by gnardini** [CardinalNow/Android-CircleProgressIndicator#3]
The library looks great, but I can't include it with gradle, I have the following error, any possible solutions?

Error:(69, 13) Failed to resolve: com.dlazaro66.wheelindicatorview:WheelIndicatorView:1.0.0
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by johnhiott** [comment]
That's not exactly how you would do that. You need to import the project then use the command
```
compile project (':libraryName')
```

Or try using jitpack you can look [here](https://jitpack.io/#CardinalNow/Android-CircleProgressIndicator) to figure out how to do that.

**Comment by IshanPunchihewa** [comment]
i also have the same issue.. jonhiott i dont understand wat  u saying

**Comment by axemorgan** [comment]
The project isn't hosted on Maven Central, so if you want to get the project directly through Gradle without having to import the project files, you'll need to add JitPack as a repository, like this:
```
repositories {
        // ...
        maven { url "https://jitpack.io" }
    }
```

Then declare the dependency like this:
```
compile 'com.github.CardinalNow:Android-CircleProgressIndicator:-SNAPSHOT' 
```
