### ISSUE TITLE
Error when building Gradle

### ISSUE THREAD

**Issue by skleung** [CardinalNow/Android-CircleProgressIndicator#5]
I've followed the instructions here: https://android-arsenal.com/details/1/1446 but am getting a Gradle failure to sync.

**Comment by kingws** [comment]
What is your Gradle error?

Sent from my iPhone
-Shane

**Comment by skleung** [comment]
I've attached a screenshot
![screen shot 2015-08-03 at 9 42 16 am](https://cloud.githubusercontent.com/assets/3238124/9042529/35a2947c-39c4-11e5-894b-a7bd145d11bd.png)

Here is how I'm including it in the build file:
```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.CardinalNow:Android-CircleProgressIndicator:78ba1d2066'
}
```

**Comment by skleung** [comment]
Ah I figured it out, I had neglected to include `jCenter()` as I learned from jitpack.io's [example](https://github.com/jitpack/android-example).
```
repositories {
    jCenter()
    maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.CardinalNow:Android-CircleProgressIndicator:78ba1d2066'
}
```

Might I suggest including these details in the `README.md` for future users?
