### ISSUE TITLE
Gradle sync has a warning and gradle build fails

### ISSUE THREAD

**Issue by danielyaa5** [CardinalNow/Android-CircleProgressIndicator#6]
Heres the code in my module build.gradle file.
<img width="727" alt="screen shot 2015-10-20 at 7 27 56 pm" src="https://cloud.githubusercontent.com/assets/6629098/10623813/71a901de-7760-11e5-8584-6ea7171148a0.png">
Heres the resulting gradle sync warning
<img width="1600" alt="screen shot 2015-10-20 at 7 15 07 pm" src="https://cloud.githubusercontent.com/assets/6629098/10623820/7f59872c-7760-11e5-96b3-883c6918d2db.png">
And finally here the compilation failure 
<img width="1367" alt="screen shot 2015-10-20 at 7 14 55 pm" src="https://cloud.githubusercontent.com/assets/6629098/10623824/8b3dc7e2-7760-11e5-9f25-60a2ee1a45e1.png">

**Comment by whaleswallace** [comment]
same issue i have here too

**Comment by Sara-Tareq** [comment]
I also have this problem , this is since the CircleProgressIndicator is setting the applicationId

**Comment by kaladivo** [comment]
I've got the same error too

**Comment by mitsus** [comment]
I've solved adding in in project androidautowire.jar into /libs folder. Witout use Gradle and Maven.

**Comment by jacobhyphenated** [comment]
I think the correct resolution here is to remove the dependency on androidautowire.jar.  I'll start working on that change.

**Comment by jacobhyphenated** [comment]
Fixed. Use the tag v0.1 for the new version that does not include this dependency.
