### ISSUE TITLE
How to change progressbar's width and height?

### ISSUE THREAD

**Issue by HaobinXu** [CardinalNow/Android-CircleProgressIndicator#9]
When I set the progressbar width or height like "android:layout_width="10.0dp"", the progressbar will dismiss(because too small).How can I fix it?

**Comment by jacobhyphenated** [comment]
If you want to change the size of the circular progress bar, you need to change the radius, not the width or height.

In a resources xml, override the `circleProgressRadius` dimension value.  In your case, if you want a radius of 10dp and a thickness of 2dp, use:

```
<dimen name="circleProgressRadius">10dp</dimen>
<dimen name="circleProgressThickness">2dp</dimen>
```

See the Readme for other values configurable values.

**Comment by HaobinXu** [comment]
Thank you!
